services:
  web:
    build: .
    volumes:
      - "./:/var/www/html"
    depends_on:
      - courteline_mysql
    ports:
      - "80:80"

  courteline_mysql:
    container_name: courteline_mysql
    image: mysql:9
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - "./database/db_dev.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: courteline_mysql

#   traefik:
#     image: traefik:v3.0
#     restart: always
#     command: 
#       - "--providers.docker"
#       - "--entrypoints.web.address=:80"
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - web

# networks:
#   web:
#     external: true